export const indonesian: Record<string, string> = {
  "Selected projects": "Proyek pilihan",
  "At a glance":"Ringkasan proyek", "Objective":"Tujuan", "Deliverable":"Hasil pengerjaan", "Key findings":"Temuan utama",
  "How the project was built":"Langkah pengerjaan", "Data used":"Data yang digunakan", "What to keep in mind":"Catatan penting", "Supporting visuals":"Visual pendukung", "Overview, findings & process":"Ringkasan, temuan & proses",


  "Live demo":"Demo langsung", "Open in Tableau":"Buka di Tableau", "Close live demo":"Tutup demo", "Loading dashboard…":"Memuat dashboard…",

  "Explore the dashboard filters. On a small screen, scroll inside the dashboard or open it in Tableau.":"Coba filter pada dashboard. Di layar kecil, geser area dashboard atau buka di Tableau.",

  "If the dashboard does not appear, open it in Tableau.":"Jika dashboard tidak muncul, buka langsung di Tableau.",

  "Previous image":"Gambar sebelumnya", "Next image":"Gambar berikutnya",



  "The question, the work, and what the evidence shows.": "Pertanyaan, proses pengerjaan, dan hasil analisisnya.",

  "Data Analyst & Data Engineer Enthusiast": "Antusias di Bidang Analisis & Rekayasa Data",

  "Interested in internships & early-career opportunities": "Terbuka untuk kesempatan magang dan karier awal",

  "Kementerian Pertanian Republik Indonesia": "Kementerian Pertanian Republik Indonesia",

  "Data workflow": "Alur pengolahan data",

  "Reply to:":"Balas ke:", "Let’s connect — portfolio enquiry":"Mari terhubung — pertanyaan portofolio",

  "Home":"Beranda", "About":"Tentang", "Projects":"Proyek", "Experience":"Pengalaman", "Volunteer":"Relawan", "Certifications":"Sertifikasi", "Skills":"Keahlian", "Contact":"Kontak",

  "Skip to content":"Lewati ke konten", "Main navigation":"Navigasi utama", "Navigation menu":"Menu navigasi", "Revaldy Arrahman, home":"Revaldy Arrahman, beranda",

  "INFORMATION SYSTEMS / DATA":"SISTEM INFORMASI / DATA", "PERSONAL PORTFOLIO":"PORTOFOLIO PRIBADI", "Hello, I’m Revaldy.":"Halo, saya Revaldy.", "Data Analyst &":"Peminat Analisis Data &", "Data Engineer Enthusiast":"Rekayasa Data",

  "I’m an Information Systems student working with SQL, Python, Tableau, and Power BI to analyze data and build dashboards.":"Saya mahasiswa Sistem Informasi yang menggunakan SQL, Python, Tableau, dan Power BI untuk menganalisis data dan membuat dashboard.",

  "View projects":"Lihat proyek", "Download CV":"Unduh CV", "CV coming soon":"CV segera tersedia", "Professional focus":"Fokus profesional", "MY FOCUS":"FOKUS SAYA", "From raw data":"Dari data mentah", "to clear":"menjadi", "understanding.":"pemahaman yang jelas.", "Prepare the data":"Siapkan data", "Find the patterns":"Temukan pola", "Explain the insights":"Jelaskan temuan", "ANALYTICS + ENGINEERING":"ANALISIS + REKAYASA DATA", "Interested in internships &":"Terbuka untuk magang &", "early-career opportunities":"peluang awal karier", "Explore the work below":"Jelajahi karya saya",

  "ABOUT":"TENTANG", "About me":"Tentang saya", "I’m an Information Systems student with an interest in the whole data journey: how it’s prepared, what it tells us, and how we communicate it.":"Saya mahasiswa Sistem Informasi yang tertarik pada seluruh proses pengolahan data: cara menyiapkannya, informasi yang dihasilkan, dan cara menyampaikannya.",

  "In team projects, I contribute Python code for data analysis. I’ve also taught Excel to PAUD teachers and introduced Power BI to students at SMK Negeri 22 Jakarta.":"Dalam proyek tim, saya berkontribusi menulis kode Python untuk analisis data. Saya juga pernah mengajar Excel kepada guru PAUD dan memperkenalkan Power BI kepada siswa SMK Negeri 22 Jakarta.", "Data analytics":"Analisis data", "Data engineering":"Rekayasa data", "ACADEMIC FOUNDATION":"PENDIDIKAN", "Information Systems":"Sistem Informasi", "GPA":"IPK", "SEMESTER 7":"SEMESTER 7", "AS LISTED IN PORTFOLIO":"SESUAI DATA PORTOFOLIO",

  "SELECTED WORK":"PROYEK PILIHAN", "Questions explored through data.":"Menjawab pertanyaan melalui data.", "Three projects. The question, the work, and what the evidence shows.":"Tiga proyek: pertanyaan, proses pengerjaan, dan hasil analisisnya.", "My contribution:":"Kontribusi saya:", "Project tools":"Tools proyek", "View on GitHub":"Lihat di GitHub", "Enlarge":"Perbesar", "View case study":"Lihat studi kasus", "Close case study":"Tutup studi kasus", "Objective, process & findings":"Tujuan, proses & temuan", "01 / The question":"01 / Pertanyaan", "02 / The data":"02 / Data", "03 / The process":"03 / Proses", "04 / The output":"04 / Hasil", "05 / The findings":"05 / Temuan", "Reading the results carefully":"Memahami hasil dengan cermat",

  "Customer churn analysis":"Analisis churn pelanggan", "Analytics & predictive modeling":"Analisis & pemodelan prediktif", "Understanding why customers leave, and making churn risk easier to explore.":"Memahami alasan pelanggan berhenti berlangganan dan memudahkan penelusuran risiko churn.", "Identify customer churn risk and understand the main drivers in a Telco customer dataset.":"Mengidentifikasi risiko churn pelanggan dan memahami faktor utamanya pada dataset pelanggan Telco.", "Telco customer dataset. The project contains 7,032 clean records.":"Dataset pelanggan Telco. Proyek ini menggunakan 7,032 data pelanggan yang telah dibersihkan.", "Clean the data with SQL and prepare it for analysis in SQLite.":"Membersihkan data dengan SQL dan menyiapkannya untuk analisis di SQLite.", "Explore customer patterns and train a balanced logistic regression model in Python.":"Mengeksplorasi pola pelanggan dan melatih model regresi logistik dengan penyeimbangan kelas di Python.", "Present churn drivers and customer risk scores in a Tableau dashboard.":"Menyajikan faktor churn dan skor risiko pelanggan melalui dashboard Tableau.", "A customer churn risk dashboard with contract, tenure, payment method, feature importance, and customer risk views.":"Dashboard risiko churn pelanggan dengan tampilan kontrak, lama berlangganan, metode pembayaran, pengaruh fitur, dan risiko pelanggan.", "Monthly contracts have a 42.7% churn rate, compared with 2.85% for two-year contracts. Overall churn is 26.58%.":"Kontrak bulanan memiliki tingkat churn 42.7%, dibandingkan 2.85% pada kontrak dua tahun. Tingkat churn keseluruhan adalah 26.58%.", "The model reports 77% recall and 50% precision. These measures describe different trade-offs in identifying customers at risk.":"Model mencatat recall 77% dan precision 50%. Kedua metrik ini menunjukkan pertimbangan yang berbeda dalam mengidentifikasi pelanggan berisiko.", "clean customer records":"data pelanggan bersih", "Tableau · Original project dashboard":"Tableau · Dashboard asli proyek",

  "MBG sentiment analysis":"Analisis sentimen MBG", "Natural language processing":"Pemrosesan bahasa alami", "Exploring sentiment in Indonesian social media posts about the MBG program.":"Mengeksplorasi sentimen unggahan media sosial berbahasa Indonesia tentang program MBG.", "Collaborated with the team to develop the Python code for data analysis.":"Bekerja bersama tim untuk mengembangkan kode Python bagi analisis data.", "Classify positive and negative sentiment in social media posts about the MBG program.":"Mengklasifikasikan sentimen positif dan negatif dalam unggahan media sosial tentang program MBG.", "1,875 positive and negative posts, with automatic sentiment labels. The notebook test set contains 375 posts.":"Sebanyak 1,875 unggahan positif dan negatif dengan label sentimen otomatis. Data uji pada notebook berisi 375 unggahan.", "Clean, tokenize, and stem Indonesian text using NLTK and Sastrawi.":"Membersihkan teks berbahasa Indonesia, melakukan tokenisasi dan stemming menggunakan NLTK serta Sastrawi.", "Create automatic sentiment labels and represent the text with TF-IDF.":"Membuat label sentimen otomatis dan merepresentasikan teks dengan TF-IDF.", "Train a Multinomial Naïve Bayes classifier and evaluate the test predictions.":"Melatih model klasifikasi Multinomial Naïve Bayes dan mengevaluasi prediksi pada data uji.", "A text classification notebook, confusion matrix, and word clouds for positive and negative sentiment.":"Notebook klasifikasi teks, confusion matrix, dan word cloud untuk sentimen positif serta negatif.", "The notebook reports 81.07% test accuracy. The confusion matrix shows that negative-class recall needs improvement.":"Notebook mencatat akurasi pengujian 81.07%. Confusion matrix menunjukkan bahwa recall kelas negatif masih perlu ditingkatkan.", "The accompanying paper reports 90.11% accuracy, while the notebook output in the deck reports 81.07%. The labels are automatically generated, rather than human-verified ground truth.":"Makalah mencatat akurasi 90.11%, sedangkan output notebook pada materi portofolio mencatat 81.07%. Label dibuat otomatis dan belum diverifikasi manusia sebagai acuan kebenaran.", "social media posts":"unggahan media sosial", "Python · Notebook confusion matrix":"Python · Confusion matrix notebook", "Words in the positive and negative sentiment data":"Kata-kata dalam data sentimen positif dan negatif",

  "East Java poverty classification":"Klasifikasi kemiskinan Jawa Timur", "Academic team project":"Proyek akademik tim", "Examining regional socioeconomic indicators through classification.":"Mengkaji indikator sosial ekonomi wilayah melalui klasifikasi.", "Explore poverty categories across East Java's cities and regencies in an academic team project.":"Mengeksplorasi kategori kemiskinan di kota dan kabupaten Jawa Timur dalam proyek akademik tim.", "Regional socioeconomic data. The deck does not name a specific originating dataset.":"Data sosial ekonomi wilayah. Materi portofolio tidak menyebutkan secara spesifik dataset asalnya.", "Compare class statistics across regional socioeconomic indicators.":"Membandingkan statistik kelas pada indikator sosial ekonomi wilayah.", "Calculate Bayes probabilities and evaluate classifications using Python and Orange.":"Menghitung probabilitas Bayes dan mengevaluasi klasifikasi menggunakan Python serta Orange.", "Review the paper's five-fold cross-validation results.":"Meninjau hasil validasi silang lima lipatan dalam makalah.", "Regional classification analysis and Orange evaluation figures in the academic paper.":"Analisis klasifikasi wilayah dan gambar evaluasi Orange dalam makalah akademik.", "The paper identifies Sampang, Bangkalan, and Sumenep in the poverty class. It reports 92.1% accuracy and an AUC of 0.276.":"Makalah mengidentifikasi Sampang, Bangkalan, dan Sumenep dalam kelas kemiskinan. Akurasi yang dilaporkan sebesar 92.1% dengan AUC 0.276.", "The low reported AUC means the accuracy figure alone does not demonstrate reliable class discrimination.":"Nilai AUC yang rendah menunjukkan bahwa akurasi saja belum membuktikan kemampuan model untuk membedakan kelas secara andal.", "cross-validation in paper":"validasi silang dalam makalah", "Orange · Original paper figure":"Orange · Gambar asli makalah", "Evaluation results as reported in the paper":"Hasil evaluasi yang dilaporkan dalam makalah",

  "EXPERIENCE":"PENGALAMAN", "Working with data in practice.":"Mengolah data dalam dunia kerja.", "PROJECT DATA SUPPORT":"DUKUNGAN DATA PROYEK", "HOK program":"Program HOK", "December 2025":"Desember 2025", "February 2026":"Februari 2026", "April 2022":"April 2022", "June 2022":"Juni 2022", "Managed and validated sugarcane farmer records from regions across Indonesia for the HOK program. Processed fund disbursement through SAKTI, the Ministry of Finance system.":"Mengelola dan memvalidasi data petani tebu dari berbagai wilayah di Indonesia untuk program HOK. Memproses penyaluran dana melalui SAKTI, sistem Kementerian Keuangan.", "HOK program data workflow":"Alur data program HOK", "Farmer records":"Data petani", "Validation & processing":"Validasi & pengolahan", "Verification":"Verifikasi", "Fund disbursement via SAKTI":"Penyaluran dana via SAKTI", "My work covered data administration, validation, and fund disbursement processing through SAKTI.":"Pekerjaan saya mencakup administrasi data, validasi, dan pemrosesan penyaluran dana melalui SAKTI.", "E-Commerce Intern":"Magang E-Commerce", "Internship / PKL":"Magang / PKL", "Managed and updated product listings on Shopee and Tokopedia, keeping product information up to date across both platforms. Created product content, including promotional videos, for online listings.":"Mengelola dan memperbarui listing produk di Shopee dan Tokopedia, termasuk informasi produk di kedua platform. Membuat konten produk, termasuk video promosi, untuk listing online.", "Workplace operations with limited IT and network support.":"Mendukung operasional kerja serta kebutuhan dasar IT dan jaringan.",

  "VOLUNTEER":"RELAWAN", "Volunteering & Teaching":"Kegiatan Relawan & Mengajar", "Power BI learning session":"Sesi pembelajaran Power BI", "Volunteer instructor · Student team":"Pengajar relawan · Tim mahasiswa", "University community engagement program":"Program pengabdian masyarakat universitas", "May 2025":"Mei 2025", "Delivered a Power BI learning session for vocational high school students as part of a university community engagement program. Introduced students to the fundamentals of Power BI, data visualization, and basic dashboard creation. Collaborated with a student team to prepare and deliver the learning session.":"Mengajar Power BI kepada siswa SMK melalui program pengabdian masyarakat universitas. Memperkenalkan dasar Power BI, visualisasi data, dan pembuatan dashboard sederhana. Bekerja bersama tim mahasiswa untuk menyiapkan serta menyampaikan materi.", "Microsoft Excel for PAUD teachers":"Microsoft Excel untuk guru PAUD", "Volunteer instructor":"Pengajar relawan", "Basic Microsoft Excel training":"Pelatihan dasar Microsoft Excel", "Taught basic Microsoft Excel skills to Early Childhood Education (PAUD) teachers, helping them streamline daily administrative tasks and data management.":"Mengajarkan dasar Microsoft Excel kepada guru PAUD untuk membantu pekerjaan administrasi sehari-hari dan pengelolaan data.",

  "CERTIFICATIONS":"SERTIFIKASI", "Certifications & Training":"Sertifikasi & Pelatihan", "Training certificate":"Sertifikat pelatihan", "Institutional competency certificate":"Sertifikat kompetensi institusi", "Issued":"Diterbitkan", "Test date":"Tanggal ujian", "16 July 2024":"16 Juli 2024", "29 March 2023":"29 Maret 2023", "Completed 180 hours of training organized by Pusbang Proserti, from 19 February to 14 July 2024.":"Menyelesaikan 180 jam pelatihan yang diselenggarakan Pusbang Proserti, dari 19 Februari hingga 14 Juli 2024.", "Successfully completed the competency test in Microsoft Word, Microsoft Excel, and PowerPoint.":"Berhasil menyelesaikan uji kompetensi Microsoft Word, Microsoft Excel, dan PowerPoint.", "View certificate":"Lihat sertifikat", "SKILLS":"KEAHLIAN", "Tools I work with.":"Tools yang saya gunakan.", "Skills and tools":"Keahlian dan tools",

  "07 / WHAT’S NEXT":"07 / LANGKAH SELANJUTNYA", "Let’s work":"Mari bekerja", "with":"dengan", "I’m interested in Data Analyst and Data Engineer internships and early-career opportunities.":"Saya terbuka untuk peluang magang dan awal karier sebagai Data Analyst atau Data Engineer.", "Start a conversation.":"Mari berdiskusi.", "Have an opportunity or a project in mind? I’d love to hear about it.":"Punya peluang kerja atau ide proyek? Saya senang mendengarnya.", "Your email":"Email Anda", "Your message":"Pesan Anda", "Tell me a little about what you have in mind…":"Ceritakan sedikit tentang peluang atau proyek Anda…", "Open email draft":"Buka draf email", "Opens your email app with a draft addressed to Revaldy. Send it there to get in touch.":"Membuka aplikasi email dengan draf untuk Revaldy. Kirim melalui aplikasi tersebut untuk menghubungi saya.", "Please write a message, not just spaces.":"Tuliskan pesan, bukan hanya spasi.", "Draft requested. If your email app didn’t open, use the email link to get in touch.":"Draf sudah diminta. Jika aplikasi email tidak terbuka, gunakan tautan email untuk menghubungi saya.", "DATA ANALYTICS & ENGINEERING":"ANALISIS & REKAYASA DATA", "Back to top":"Kembali ke atas",

  "Image preview":"Pratinjau gambar", "Fit to screen":"Sesuaikan layar", "Zoom in":"Perbesar", "Close image preview":"Tutup pratinjau gambar", "Loading image…":"Memuat gambar…", "The image could not be loaded. Close the preview and try again.":"Gambar gagal dimuat. Tutup pratinjau dan coba lagi.", "Switch to dark mode":"Aktifkan mode gelap", "Switch to light mode":"Aktifkan mode terang", "Choose language":"Pilih bahasa",

  "Original Tableau customer churn dashboard showing contract, tenure, payment method, and customer risk analysis":"Dashboard Tableau asli berisi analisis kontrak, lama berlangganan, metode pembayaran, dan risiko churn pelanggan",

  "Original notebook confusion matrix: 274 positive posts classified correctly and 30 negative posts classified correctly, with 71 misclassified negative posts":"Confusion matrix notebook asli: 274 unggahan positif dan 30 unggahan negatif diklasifikasikan dengan benar, dengan 71 unggahan negatif salah klasifikasi",

  "Original project word clouds for positive and negative Indonesian sentiment":"Word cloud asli proyek untuk sentimen positif dan negatif berbahasa Indonesia",

  "Original Orange scatter plot from the academic paper comparing socioeconomic indicators for East Java regions":"Scatter plot Orange asli dalam makalah yang membandingkan indikator sosial ekonomi wilayah Jawa Timur",

  "Original Orange evaluation reporting Naïve Bayes AUC 0.276 and classification accuracy 0.921":"Evaluasi Orange asli dengan AUC Naïve Bayes 0.276 dan akurasi klasifikasi 0.921",

  "Photo collage of the Power BI learning session at SMK Negeri 22 Jakarta, showing classroom teaching and student practice with the university student team":"Kolase foto pembelajaran Power BI di SMK Negeri 22 Jakarta, berisi kegiatan mengajar dan praktik siswa bersama tim mahasiswa",

  "Microsoft Excel training for PAUD teachers at HIMPAUDI Cempaka Putih, with participants using laptops during the session":"Pelatihan Microsoft Excel bagi guru PAUD di HIMPAUDI Cempaka Putih dengan peserta menggunakan laptop",

  "Revaldy Arrahman's Kominfo training certificate for Database Design and Database Programming with SQL, issued 16 July 2024":"Sertifikat pelatihan Kominfo Revaldy Arrahman untuk Database Design and Database Programming with SQL, diterbitkan 16 Juli 2024",

  "Revaldy Arrahman's LPK LCC institutional competency certificate for Microsoft Office, with test date 29 March 2023":"Sertifikat kompetensi institusi LPK LCC Revaldy Arrahman untuk Microsoft Office, dengan tanggal ujian 29 Maret 2023"

};

